### ISSUE TITLE
[Suggestion]: Ability to group items by creative tab rather than mod

### ISSUE THREAD

**Issue by NyanMC** [Fuzss/completionistsindex#11]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.4

### Mod Version(s) (Optional)

20.4.1

### Suggestion (Required)

I really like the concept of this mod, however it can be a bit annoying when a single category in the index has a lot of items. For instance, grouping all >1000 vanilla items into a single Minecraft category makes it very annoying to scroll through, and this also leads to a fair bit of wasted space on the index's category menu when no serverside mods are installed, making Minecraft the only category in that menu. This can work both ways, sometimes mods have very little content which creates an entire tab with just a single item, or very few items.

Therefore, my suggestion is to add an option to group items into categories based on what creative tab they appear in, adding items without a tab to their own category. When an item is in multiple creative tabs, it could either appear in multiple categories or in the category corresponding to the first creative tab it appears in, whichever is easier to implement.

**Comment by Fuzss** [comment]
Added in v21.3.0.
