### ISSUE TITLE
[Bug]: Incompatible with Not Enough Recipe Book

### ISSUE THREAD

**Issue by QwertRvg** [Fuzss/completionistsindex#12]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.0

### Minimal Setup (Required)

Yes

### Notes (Required)

So the Not Enough Recipe Book mod fully removes the Recipe Book, not just hides it. It seems like the functionality of the Recipe Book is directly tied to the Index, as the Index Inventory Button gets completely hidden.

### latest.log (Required)

https://pastebin.com/HPyE1i2B

**Comment by Fuzss** [comment]
That's an issue on their end, they must check the resource location of the button they remove.

**Comment by QwertRvg** [comment]
so this issue still persists but in a different form
![image](https://github.com/user-attachments/assets/00f0946b-9b12-40bf-9f97-fda120156ddd)

and it doesnt just happen with NERB
when REI disables the Recipe Book, this also moves the Index Book

**Comment by Fuzss** [comment]
Still an issue on their end. They must check the resource location of the button.

For now you can disable the button in the inventory, the index can still be accessed from the pause menu.
