### ISSUE TITLE
[Suggestion]: Scan chests/Surrounding items? Or ability to manually check boxes, or a config option to enable that

### ISSUE THREAD

**Issue by paulbevzyuk** [Fuzss/completionistsindex#2]
### Suggestion (Required)

Really awesome mod by the way, just added it to my world but it seems like the mod only checks items that are being picked up by my player, even when I move something from a chest into my inventory the mod doesn't register it. So maybe it would be cool to have the option to manually check the boxes so that I can keep the Completionist's Index up to date?

Or if the mod could scan chests or items that I move from the chests into my inventory that could be a worthwhile feature

Thanks a lot for the mod!

**Comment by Fuzss** [comment]
Thanks for the suggestion! This would require a server-side component, since it's not covered by vanilla's statistics system. The goal of Completionist's Index is the be a client-side mod that also works on vanilla servers, so essentially a better statistics screen.

**Comment by paulbevzyuk** [comment]
So something like a checkbox for each item would require a server sided
component ?

**Comment by Fuzss** [comment]
Yes, the server needs to store that you clicked the checkbox. The client doesn‘t store any data, everything would be lost after restarting the game.
