### ISSUE TITLE
[Suggestion]: Please add a whitelist to the config file

### ISSUE THREAD

**Issue by Kelpiesaurus** [Fuzss/completionistsindex#8]
### Mod Loader (Optional)

Forge

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

8.0.0

### Suggestion (Required)

Would you please consider adding a whitelist to the config file? I am hoping to use the index as a checklist for items to be collected & displayed in museum exhibits, and a whitelist would be much easier to fill than the blacklist.

**Comment by Fuzss** [comment]
Added in v21.3.0.
